[package]
name = "feos"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "feos"
path = "src/main.rs"

[lib]
name = "main_server"
path = "src/lib.rs"

[dependencies]
feos-utils = { path = "utils" }
vm-service = { path = "services/vm-service" }
host-service = { path = "services/host-service" }
image-service = { path = "services/image-service" }
task-service = { path = "services/task-service" }
container-service = { path = "services/container-service" }
feos-proto = { workspace = true }

# Workspace dependencies
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
nix = { workspace = true }
clap = { workspace = true, features = ["derive"] }
dotenvy = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
libc = { workspace = true }
rtnetlink = { workspace = true }
netlink-packet-route = { workspace = true }
pnet = { workspace = true }
dhcproto = { workspace = true }
socket2 = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
termcolor = { workspace = true }

[dev-dependencies]
feos-utils = { path = "utils" }
vm-service = { path = "services/vm-service" }
image-service = { path = "services/image-service"}
host-service = { path = "services/host-service"}
anyhow = { workspace = true }
nix = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
tokio-stream = { workspace = true }
prost = { workspace = true }
hyper-util = { workspace = true }
once_cell = { workspace = true }
tower = { workspace = true }
tempfile = { workspace = true }

[features]
git-version = ["feos-utils/git-version"]