#!/bin/bash

set -e

FEOS_CONFIG=${1:-default}

thisDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
TARGET_DIR=${TARGET_DIR:-$thisDir/../../target}
ROOTFS_DIR=${thisDir}/../../target/rootfs

[ ! -d "${TARGET_DIR}" ] && echo "Directory: '$TARGET_DIR' does not exist." && exit 1

source utils.sh
source ../kernel/config.sh

pushd $ROOTFS_DIR 
echo "Create initramfs folder structure"
mkdir -pv {etc,var,lib64,lib,run,tmp} usr/{bin,lib,sbin} lib/x86_64-linux-gnu usr/lib/x86_64-linux-gnu

mkdir -pv {proc,dev,sys}

cat <<EOF >>etc/hosts
127.0.0.1    localhost
127.0.1.1    feos
::1          localhost feos
EOF

echo "feos" > etc/hostname


echo "Install libraries for FeOS (copy from host)"
install_libs $ROOTFS_DIR/bin/feos

echo "Create initramfs.zst"
find . -print0 | cpio --create --format=newc --null | zstd -3 > "${TARGET_DIR}/initramfs.zst"

popd
