#!/bin/bash

set -e

workingDir=$(mktemp -d)
thisDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

function clean {
    rm -rf $workingDir
}
trap clean EXIT

source config.sh

pushd $workingDir

KERNEL_MAJOR_VERSION=$(echo $KERNEL_VERSION | cut -d"." -f1)
echo "Downloading Linux Kernel $KERNEL_VERSION"
wget -qO- --show-progress "https://cdn.kernel.org/pub/linux/kernel/v${KERNEL_MAJOR_VERSION}.x/linux-${KERNEL_VERSION}.tar.xz" |
    tar xJ
cp "$thisDir/config/$KERNEL_CONFIG" linux-${KERNEL_VERSION}/.config
pushd linux-${KERNEL_VERSION}
make oldconfig

popd # linux src

cp linux-${KERNEL_VERSION}/.config "$thisDir/config/$KERNEL_CONFIG"

popd # working dir
