CREATE TABLE IF NOT EXISTS vms (
    -- The primary key for the VM, generated by the vm-service.
    vm_id TEXT PRIMARY KEY NOT NULL,
    -- The UUID of the root filesystem image used by this VM.
    image_uuid TEXT NOT NULL,
    -- The current state of the VM (e.g., 'Creating', 'Running'). Stored as text for readability.
    state TEXT NOT NULL,
    -- The last human-readable status message associated with the VM's state.
    last_msg TEXT,
    -- The process ID (PID) of the running hypervisor process, if any.
    pid INTEGER,
    -- A binary blob containing the serialized VmConfig protobuf message.
    -- This allows for flexible configuration changes without schema migrations.
    config_blob BLOB NOT NULL,
    -- Timestamp of when the record was first created.
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- Timestamp of the last update to the record.
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- A trigger to automatically update the 'updated_at' timestamp whenever a row is modified.
CREATE TRIGGER IF NOT EXISTS trigger_vms_updated_at
AFTER UPDATE ON vms
FOR EACH ROW
BEGIN
    UPDATE vms SET updated_at = CURRENT_TIMESTAMP WHERE vm_id = OLD.vm_id;
END;
